// <auto-generated />
using BarsAPI.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BarsAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210506215343_AddImage")]
    partial class AddImage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BarsAPI.Models.BarDetails", b =>
                {
                    b.Property<int>("BarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Deposit")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BarId");

                    b.ToTable("BarDetails");

                    b.HasData(
                        new
                        {
                            BarId = 1,
                            Address = "Triq il-Knisja, Għarb",
                            Deposit = 2.00m,
                            Name = "Gharb Rangers Football Club",
                            Phone = 21565666,
                            Website = "https://gharb-rangers-bar-restaurant.business.site/",
                            image = "https://lh3.googleusercontent.com/p/AF1QipPt_KIvv06p72QaiwV7KYrhB8mMz-OIbjg5NJTr=w600-h0"
                        },
                        new
                        {
                            BarId = 2,
                            Address = "Enrico Mizzi, Victoria Għawdex",
                            Deposit = 1.50m,
                            Name = "TaPie",
                            Phone = 21535455,
                            Website = "https://artzid.com/artwork/tapies-bar-gozo/",
                            image = "https://content.visitgozo.com/content/2016/09/1-50e296df877544ddaacf302d7867bee7.jpg"
                        },
                        new
                        {
                            BarId = 3,
                            Address = "Enrico Mizzi, Victoria Għawdex",
                            Deposit = 3.00m,
                            Name = "Rizzles Cafe",
                            Phone = 21552464,
                            Website = "https://timetoeat.com.mt/rizzles-cafe/menu",
                            image = "https://maltamenu.com.mt/images/restaurants/rizzles-cafe-dolceria-gozo-0.jpg"
                        },
                        new
                        {
                            BarId = 4,
                            Address = "Triq Victoria, Għawdex",
                            Deposit = 1.00m,
                            Name = "Glory of England Bar",
                            Phone = 21552659,
                            Website = "https://www.visitgozo.com/directory/bars/glory-of-england-bar/",
                            image = "https://c8.alamy.com/comp/F2CFGE/malta-31-december-2014-on-the-smaller-island-of-gozo-even-here-the-F2CFGE.jpg"
                        },
                        new
                        {
                            BarId = 5,
                            Address = "Triq tal-Ghajn, Il-Munxar",
                            Deposit = 5.00m,
                            Name = "La Grotta",
                            Phone = 99007070,
                            Website = "https://www.lonelyplanet.com/malta/xlendi/nightlife/la-grotta/a/poi-dri/1136243/1316072",
                            image = "https://scontent.fmla2-1.fna.fbcdn.net/v/t31.18172-8/23000092_1530772327016007_2975362536196116889_o.jpg?_nc_cat=109&ccb=1-3&_nc_sid=09cbfe&_nc_ohc=_uq44o1bVY8AX8XkTok&_nc_oc=AQki83syHeVUTOOYR1ARMiBR2I5kPLb-q7a8d8A-BK5pXxxlVfzUFmRiCZ9TucfCeaY&_nc_ht=scontent.fmla2-1.fna&oh=8b40d688ce5413c5c340f8b115724589&oe=60BB7622"
                        },
                        new
                        {
                            BarId = 6,
                            Address = "10, Triq Il-Vittorja, Mgarr",
                            Deposit = 4.50m,
                            Name = "Gleneagles",
                            Phone = 21556543,
                            Website = "https://gleneagles.com/",
                            image = "https://restaurantguidemalta.com/wp-content/uploads/2019/09/The-Gleneagles-Bar-10-Victoria-Road-Mgarra-Gozo-2.jpg"
                        },
                        new
                        {
                            BarId = 7,
                            Address = "St. Peter & St. Paul Square, Nadur",
                            Deposit = 2.20m,
                            Name = "Gebuba",
                            Phone = 79470141,
                            Website = "https://www.visitgozo.com/directory/bars/gebuba-bar/",
                            image = "https://brewhaus.com.mt/wp-content/uploads/2018/02/Gebuba-Bar.jpg"
                        },
                        new
                        {
                            BarId = 8,
                            Address = "Triq Il Knisja, Xagħra",
                            Deposit = 3.70m,
                            Name = "Coronation Bar",
                            Phone = 27440867,
                            Website = "https://business.google.com/v/coronation-bar-coronations/010526285549816301694/323c/_?caid=12095768560&agid=118149983404&gclid=Cj0KCQjwvr6EBhDOARIsAPpqUPHJSgZ8Cj7smlhxSOL-UQx2T1yckTPYrdhA9pINQeytXCxqteOocJkaAld2EALw_wcB&gclid=Cj0KCQjwvr6EBhDOARIsAPpqUPHJSgZ8Cj7smlhxSOL-UQx2T1yckTPYrdhA9pINQeytXCxqteOocJkaAld2EALw_wcB",
                            image = "https://www.maltaphotos.com/wp-content/uploads/2017/10/349-Gozo-Xaghra-Tradition-Coronation-Bar-British-.jpg"
                        },
                        new
                        {
                            BarId = 9,
                            Address = "Triq ir-Repubblika, Victoria",
                            Deposit = 1.15m,
                            Name = "Ritz Snack Bar",
                            Phone = 21333444,
                            Website = "https://www.facebook.com/ritzbarvictoria/",
                            image = "https://content.visitgozo.com/content/2016/09/13962581_1643113649332592_7674823205499219512_n.jpg"
                        },
                        new
                        {
                            BarId = 10,
                            Address = "Pjazza President J.F. Kennedy, Victoria",
                            Deposit = 3.35m,
                            Name = "Flamingo Bar",
                            Phone = 21553704,
                            Website = "https://www.visitgozo.com/directory/bars/flamingo-bar/",
                            image = "https://scontent.fmla2-1.fna.fbcdn.net/v/t31.18172-8/12493763_956092074446027_7567742160996404046_o.png?_nc_cat=109&ccb=1-3&_nc_sid=09cbfe&_nc_ohc=JnqOBKwjxOAAX_ecHmN&_nc_ht=scontent.fmla2-1.fna&oh=1f82b707f54c0efe411d635c26b3e3c8&oe=60BAAD14"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
